### ISSUE TITLE
Single Item Mode causes breakage?

### ISSUE THREAD

**Issue by trowpa** [leekelleher/umbraco-nested-content#62] opened 2016-04-21 00:12 UTC
If we have existing code using a nested content datatype such as `Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("PropertyName");`

Then...down the road - someone changes the min/max  from 0/3  to 1/1 - it seems the existing code breaks until someone change the above to 
`Model.Content.GetPropertyValue<IPublishedContent>("PropertyName");`

Or am I missing something?  This seems like a dangerous "feature".  Can we fix this?  Or am I just using this wrong?

**Comment by leekelleher** [comment] 2016-04-21 09:24
@trowpa Thanks for raising it. This is an intended feature of Nested Content, not a bug.

It's true that if someone were to change the data-type's configuration, it may break the front-end implementation, but the same could be said if they were to switch the underlying property-editor, (which leads to asking, why would someone do that?)

Altering data-type configuration post-implementation will always carry a risk - this isn't limited to Nested Content.

**Comment by trowpa** [comment] 2016-04-21 12:03
It's understood that changing an underlying property editor would carry risk.

However, changing min-max values is what i consider tweaking validation - (allow up to 2 items now - but allow up to 3 later if we need it)  - those things i don't think anyone expects to break the code.

I think the assumption that most people would have is that if a property editor returns a datatype of "x" , it would always return a datatype of "x" no matter if there is 1 or 3 of them.

Perhaps I could make a feature request to change property converters that would allow it to work either way a bit of "backwards compatability":

**If you are confident the nested content instance will ONLY return one and only one item**, you could use the `Model.Content.GetPropertyValue<IPublishedContent>("PropertyName");`

Returns: 

0 items - `Null`
1 item:  The single`IPublishedContent`.
2 or more items: any of the following as long as it's documented and predicable:
- FirstOrDefault
- null
- throw an error

**If you know it will return more than one item, or not sure that it might some day** - you could choose to use the`Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("PropertyName");`

Returns :

0 items:  `Null`or `Enumerable.Empty<IPublishedContent>()`
1 item - `IEnumerable<IPublishedContent>` with that one item in it
2 or more items:  `IEnumerable<IPublishedContent>`

**Comment by mattbrailsford** [comment] 2016-04-21 12:11
I would agree that people will change the min/max as the client says they want more, but this would generally only occur when you say have a min/max of 0-3 and want to make it 0-4 or something, it's highly unlikely that anyone will change from 0-3 to 1 and only 1 which is what enables single item mode.

It is possible to have multiple value resolves for resolving different types so what you suggest is possible, but it'll likely be low priority for us, as like I say, this seems a bit of an edge case.

If you want to submit a PR though, we will happily review it.

**Comment by mattbrailsford** [comment] 2016-04-21 13:03
In fact, it just occurred to me that someone has already done that PR which has already been merged in (this was to do with Models Builder not liking a single value converter returning multiple types so different problem, but same solution) https://github.com/leekelleher/umbraco-nested-content/tree/develop/src/Our.Umbraco.NestedContent/Converters

So the answer for the time being is to use the latest nightly here https://ci.appveyor.com/project/leekelleher/umbraco-nested-content/build/artifacts and the final fix will be in the next release.

**Closed as completed by mattbrailsford** 2016-04-21 13:03 UTC
Labels: not-a-bug, question

**Comment by trowpa** [comment] 2016-04-21 13:11
I'll check it out.

Thanks @mattbrailsford !!!
