### ISSUE TITLE
IsSingleNestedContentProperty returns false when min value is 0 and max value is 1

### ISSUE THREAD

**Issue by markwemekamp** [leekelleher/umbraco-nested-content#105] opened 2017-02-22 12:38 UTC
Hi,
First of all, thanks for the awesome package :)

I've configured a nested content with a minimum of 0 items and a max of 1 item. It returns a list because IsSingleNestedContentProperty checks if minItems = 1 and maxItems= 1. Is this implemented by design? I would expect it to return a single value when maxItems = 1 and in case it's not set a null value.

This is causing some trouble with our framework that generates strongly typed models.

**Comment by leekelleher** [comment] 2017-02-22 13:01
@markwemekamp Thanks for getting in touch.  The quick answer is, yes it is by design.
The thinking is that if you explicitly want a single item, you'd set the minItems/maxItems to 1.

I'm interested in understanding why you have `minItems` set to 0, rather than 1?

**Comment by markwemekamp** [comment] 2017-02-22 13:09
The initial reason I set it to 0, is because the value is optional and I don't want to display the fields unless they're needed. 
Setting it to a minimum of 1 could also work, but I'll probably move the control to a new tab.

**Comment by leekelleher** [comment] 2017-02-22 13:13
@markwemekamp Thanks 👍 

@mattbrailsford What are your thoughts on this? I'm open to the suggestion that we could return a single `IPublishedContent` if the `maxItems=1`.

**Comment by markwemekamp** [comment] 2017-02-22 13:17
I think it already works like that:

`if (propertyType.IsSingleNestedContentProperty())
                    {
                        return processedValue.FirstOrDefault();
                    }`

But the implementation of IsSingleNestedContentProperty looks like this:

`return preValueDictionary.ContainsKey("minItems") &&
                   int.TryParse(preValueDictionary["minItems"], out minItems) && minItems == 1
                   && preValueDictionary.ContainsKey("maxItems") &&
                   int.TryParse(preValueDictionary["maxItems"], out maxItems) && maxItems == 1;`

So when we have a minimum of 0 items, it returns a list

**Comment by mattbrailsford** [comment] 2017-02-22 13:30
Happy to support the ValueConveter returning single item for 0,1 configs, but be careful editing IsSingleNestedContentProperty as I believe this triggers single item mode, which you won't want if min is set to 0

**Comment by leekelleher** [comment] 2017-08-24 12:51
Closing this request, as we don't want to introduce any features that are different to the version we migrated to (upcoming) Umbraco v7.7.0.

If you still want this feature in a future Umbraco release, please feel free to raise this on the [Umbraco issue tracker](http://issues.umbraco.org/issues/U4).

**Closed as completed by leekelleher** 2017-08-24 12:51 UTC
Labels: question, wont-fix, umbraco, umbraco77
