### ISSUE TITLE
Sort order in Multiple Media Picker is not saved

### ISSUE THREAD

**Issue by arknu** [leekelleher/umbraco-nested-content#47] opened 2016-01-21 14:31 UTC
I added a document type with a Multiple Media Picker to Nested Content (for a gallery). Normally, you can drag images around in the Multiple Media Picker property editor to change the order. This works fine in Nested Content as well, but the sort order is never saved. Hit Save and Publish and then reload the page. The images are back in the order they started in.

**Comment by leekelleher** [comment] 2016-01-22 09:51
@arknu Thanks for raising this!

@mattbrailsford I suspect this may be (somehow) related to #46?

**Comment by arknu** [comment] 2016-01-22 12:21
I wonder whether this implementation in the Umbraco media picker controller might have something to do with it? It seems to have a 500ms delay between sorting and actually updating the model.

```
//TODO: Instead of doing this with a half second delay would be better to use a watch like we do in the 
// content picker. THen we don't have to worry about setting ids, render models, models, we just set one and let the 
// watch do all the rest.
$timeout(function(){
    angular.forEach($scope.images, function(value, key){
        r.push(value.id);
    });

    $scope.ids = r;
    $scope.sync();
}, 500, false);
```

UPDATE: I should also perhaps add that it works perfectly in Archetype.

**Comment by Myster** [comment] 2016-06-13 21:58
It seems to be the last re-ordering operation that is forgotten (so work-around, make an extra re-ordering just so it can be forgotten. |-)

**Comment by leekelleher** [comment] 2016-07-08 12:14
I've tested this with the latest release (v0.3.0) and can't reproduce the issue. I suspect 

Apologies for the delay in responding to this.

Closing this one off, please feel free to re-open if you are still experiencing the issue.

**Closed as completed by leekelleher** 2016-07-08 12:14 UTC
Labels: not-a-bug
