### ISSUE TITLE
Unable to edit items after switching to MyGet package.

### ISSUE THREAD

**Issue by JimBobSquarePants** [leekelleher/umbraco-nested-content#19] opened 2015-07-02 15:21 UTC
When ever I click the + button I get the following error.

```
:10002/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1188176083:63 TypeError: Cannot set property 'id' of undefined
    at initNode (:10002/App_Plugins/NestedContent/Js/nestedcontent.controllers.js?cdv=1188176083:286)
    at Object.$scope.addNode (:10002/App_Plugins/NestedContent/Js/nestedcontent.controllers.js?cdv=1188176083:84)
    at :10002/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1188176083:74
    at :10002/umbraco/lib/angular/1.1.5/angular-mobile.js?cdv=1188176083:270
    at Object.e.$eval (:10002/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1188176083:92)
    at Object.e.$apply (:10002/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1188176083:92)
    at HTMLAnchorElement.<anonymous> (:10002/umbraco/lib/angular/1.1.5/angular-mobile.js?cdv=1188176083:269)
    at HTMLAnchorElement.x.event.dispatch (:10002/umbraco/lib/jquery/jquery.min.js?cdv=1188176083:5)
    at HTMLAnchorElement.y.handle (:10002/umbraco/lib/jquery/jquery.min.js?cdv=1188176083:5)
```

It was working with the Umbraco package but not when switched over to MyGet

**Comment by leekelleher** [comment] 2015-07-02 16:20
@JimBobSquarePants Was this an update from the previous version?

Initial thought would be to bump the ClientDependency version number, (unfortunately that's not automated).

I'll see if I can reproduce the error.

**Comment by JimBobSquarePants** [comment] 2015-07-02 18:40
It was. 

I'd already bumped the ClientDependency version number without change and manually copied the scripts, views etc from the packages folder to be sure. Unfortunately the error still remains.

Chrome Version 43.0.2357.130 m (64-bit)

**Comment by leekelleher** [comment] 2015-07-02 21:41
I can reproduce the error.  There are a few things going on, which we'll need to resolve.
1. If the Umbraco package was originally installed, then the NuGet package (via MyGet in this case) is installed, then it seems that Visual Studio will **not** overwrite the existing files. (e.g. v0.1.1 files remain).
2. Due to a change in how Nested Content, we now reference DocTypes by Alias not GUID, (see the discussion on #4), the DataType prevalues need to be re-saved. (We should look to avoid that step).
3. After manually copying over files from the extracted NuGet package, (e.g. the  "/App_Plugins" folder and assembly), then the ClientDependency version number needs to be bumped.

After that, it started to work fine.  Existing property data was still there on the node, (no data loss).

// CC'ing you in @mattbrailsford - I'm not 100% sure how to resolve the above issues.

**Comment by JimBobSquarePants** [comment] 2015-07-02 23:41
Ok....

So I _think_ I did all of the above and it's still not working. 

Could you clarify. 

> Due to a change in how Nested Content, we now reference DocTypes by Alias not GUID, (see the discussion on #4), the DataType prevalues need to be re-saved. (We should look to avoid that step).

I re-saved the datatype, is that all that entails?

Does this do anything to the db? I have completely cleared out everything and started again. Still throws the error?

**Comment by leekelleher** [comment] 2015-07-03 08:51
That's the steps that I took to get it to work last night.

We'll need to bring @kjac and @mattbrailsford in to clarify this.

**Comment by JimBobSquarePants** [comment] 2015-07-06 10:13
@leekelleher I can send you the json returned by GetNodes, PostSave, and GetContentTypes if that helps? It looks to my untrained eye that the `scope.alias` property is not being output.

**Comment by leekelleher** [comment] 2015-07-06 10:43
I'll really need @kjac or @mattbrailsford to take a look... my knowledge of the Angular side is somewhat lacking. (I believe they got notifications when I @ mention them?)

**Comment by mattbrailsford** [comment] 2015-07-06 10:52
Yup, attach the JSON and I'll take a look.

**Comment by JimBobSquarePants** [comment] 2015-07-06 11:00
@mattbrailsford Github won't let me add zip files directly so here's a dropbox link. Cheers!

https://dl.dropboxusercontent.com/u/78716633/NestedContent.zip

**Comment by mattbrailsford** [comment] 2015-07-06 11:07
Did you re-save the nested content prevalues?

**Comment by JimBobSquarePants** [comment] 2015-07-06 11:10
I went into the data type and re-saved. I did it a couple of times changing to different Document types also. Is that what you mean?

**Comment by mattbrailsford** [comment] 2015-07-06 11:13
yup, and did you resave the nested content values in the content editor?

**Comment by JimBobSquarePants** [comment] 2015-07-06 11:41
I can't edit or save preexisting items in the content tree nor add new ones.

My property containing nested content is stored in a composite document type. I have re-saved that, the doctype that is nested, and the doctypes that include the composite type. 

All JavaScript files are definitely up to date also  as I have fully cleared out and bumped client dependency.

**Comment by JimBobSquarePants** [comment] 2015-07-06 16:23
Here's the DataType prevalue saved value from the db.

```
[
  {
    "ncAlias": "HeadlineSlide",
    "ncTabAlias": "Headline Slides",
    "nameTemplate": "{{title}}"
  }
]
```

**Comment by mattbrailsford** [comment] 2015-07-06 16:27
Is this anywhere public I would be able to see it from?

**Comment by JimBobSquarePants** [comment] 2015-07-07 09:11
@mattbrailsford  I'll drop you a message on Skype with details.

**Comment by kjac** [comment] 2015-07-07 11:22
Hmmm ... looks like there's no scaffold doc type to clone. Could you please try adding a `console.log()` in the `addNode()` function of nestedcontent.controllers.js (under App_Plugins > NestedContent > Js) right after `var scaffold = $scope.getScaffold(alias);` and check the value of the scaffold - e.g. `console.log("$scope.addNode", alias, scaffold);`?

**Comment by leekelleher** [comment] 2015-07-14 21:26
Closing this issue, as @JimBobSquarePants had a Skype chat with @mattbrailsford, which they found it was a DataType config issue, and not an immediate bug with Nested Content.

**Closed as completed by leekelleher** 2015-07-14 21:26 UTC
Labels: not-a-bug
